In [66]:
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]

In [67]:
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

In [68]:
def mean_square_error(y, t):
    return 0.5 * np.sum((y-t)**2)

In [69]:
import numpy as np

In [70]:
mean_square_error(np.array(y), np.array(t))

0.09750000000000003

In [71]:
y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0]

In [72]:
mean_square_error(np.array(y), np.array(t))

0.5975

In [73]:
def cross_entropy_error(y, t):
    delta = 1e-7
    return -np.sum(t * np.log(y + delta))

In [74]:
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]

In [75]:
cross_entropy_error(np.array(y), np.array(t))

0.510825457099338

In [76]:
y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0]

In [77]:
cross_entropy_error(np.array(y), np.array(t))

2.302584092994546

In [78]:
import os, sys

In [79]:
sys.path.append(os.pardir)

In [80]:
import numpy as np

In [81]:
from dataset.mnist import load_mnist

In [82]:
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label=True)

In [83]:
print(x_train.shape)

(60000, 784)


In [84]:
print(t_train.shape)

(60000, 10)


In [85]:
train_size = x_train.shape[0]

In [86]:
batch_size = 10

In [87]:
batch_mask = np.random.choice(train_size, batch_size)

In [88]:
x_batch = x_train[batch_mask]

In [89]:
t_batch = t_train[batch_mask]

In [90]:
np.random.choice(60000, 10)

array([34422, 52733, 40491, 36231, 24293,  4871, 43330, 36437, 44179,
       40328])

In [91]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    batch_size = y.shape[0]
    return -np.sum(np.log(y[n.arange(batch_size), t] + 1e-7)) / batch_size

In [92]:
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x)
    
    for idx in range(x.size):
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        fxh1 = f(x)
        
        x[idx] = tmp_val - h
        fxh2 = f(x)
        
        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val
        
    return grad

In [93]:
def function_2(x):
    return x[0]**2 + x[1]**2

In [94]:
numerical_gradient(function_2, np.array([3.0, 4.0]))

array([6., 8.])

In [95]:
numerical_gradient(function_2, np.array([0.0, 2.0]))

array([0., 4.])

In [96]:
numerical_gradient(function_2, np.array([3.0, 0.0]))

array([6., 0.])

In [97]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x
    
    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr * grad
        
    return x

In [98]:
def function_2(x):
    return x[0]**2 + x[1]**2

In [99]:
init_x = np.array([-3.0, 4.0])

In [100]:
gradient_descent(function_2, init_x=init_x, lr=0.1, step_num=100)

array([-6.11110793e-10,  8.14814391e-10])

In [101]:
init_x = np.array([-3.0, 4.0])

In [102]:
gradient_descent(function_2, init_x=init_x, lr=10.0, step_num=100)

array([-2.58983747e+13, -1.29524862e+12])

In [103]:
init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=1e-10, step_num=100)

array([-2.99999994,  3.99999992])

In [104]:
import sys, os

In [105]:
sys.path.append(os.pardir)

In [106]:
import numpy as np

In [107]:
from common.functions import softmax, cross_entropy_error

In [108]:
from common.gradient import numerical_gradient

In [109]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [110]:
net = simpleNet()

In [111]:
print(net.W)

[[ 1.45140947  1.27938184 -0.83158468]
 [-0.50588323  0.20513671 -0.26361317]]


In [112]:
x = np.array([0.6, 0.9])

In [113]:
p = net.predict(x)

In [114]:
print(p)

[ 0.41555077  0.95225214 -0.73620266]


In [115]:
np.argmax(p)

1

In [116]:
t = np.array([0, 0, 1])

In [117]:
net.loss(x, t)

2.2591387469343256

In [118]:
def f(W):
    return net.loss(x, t)

In [119]:
dW = numerical_gradient(f, net.W)

In [120]:
print(dW)

[[ 0.19825269  0.33908262 -0.53733531]
 [ 0.29737903  0.50862393 -0.80600296]]


In [121]:
import os, sys

In [122]:
sys.path.append(os.pardir)

In [123]:
from common.functions import *

In [124]:
from common.gradient import numerical_gradient

In [125]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size, weight_init_std=0.01):
        self.params = {}
        self.params['W1'] = weight_init_std * np.random.randn(input_size, hidden_size)
        self.params['b1'] = np.zeros(hidden_size)
        self.params['W2'] = weight_init_std * np.random.randn(hidden_size, output_size)
        self.params['b2'] = np.zeros(output_size)
        
    def predict(self, x):
        W1, W2 = self.params['W1'], self.params['W2']
        b1, b2 = self.params['b1'], self.params['b2']
        
        a1 = np.dot(x, W1) + b1
        z1 = sigmoid(a1)
        a2 = np.dot(z1, W2) + b2
        y = softmax(a2)
        
        return y
    
    def loss(self, x, t):
        y = self.predict(x)
        
        return cross_entropy_error(y, t)
    
    def accuracy(self, x, t):
        y = self.predict(x)
        y = np.argmax(y, axis=1)
        t = np.argmax(t, axis=1)
        
        accuracy = np.sum(y == t) / float(x.shape[0])
        return accuracy
    
    def numerical_gradient(self, x, t):
        loss_W = lambda W: self.loss(x, t)
        
        grad = {}
        grads['W1'] = numerical_gradient(loss_W, self.params['W1'])
        grads['b1'] = numerical_gradient(loss_W, self.params['b1'])
        grads['W2'] = numerical_gradient(loss_W, self.params['W2'])
        grads['b2'] = numerical_gradient(loss_W, self.params['b2'])
        
        return grads

In [126]:
net = TwoLayerNet(input_size=784, hidden_size=100, output_size=10)

In [127]:
net.params['W1'].shape

(784, 100)

In [128]:
net.params['b1'].shape

(100,)

In [129]:
net.params['W2'].shape

(100, 10)

In [130]:
net.params['b2'].shape

(10,)

In [131]:
import numpy as np

In [132]:
from dataset.mnist import load_mnist

In [135]:
from two_layer_net import TwoLayerNet

In [136]:
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label = True)

In [ ]:
train_loss_list = []
train_acc_list = []
test_acc_list = []
iter_per_epoch = max(train_size / batch_size, 1)

In [141]:
iters_num = 100
train_size = x_train.shape[0]
batch_size = 100
learning_rate = 0.1

In [142]:
network = TwoLayerNet(input_size=784, hidden_size=50, output_size=10)

In [ ]:
for i in range(iters_num):
    batch_mask = np.random.choice(train_size, batch_size)
    x_batch = x_train[batch_mask]
    t_batch = t_train[batch_mask]
    
    grad = network.numerical_gradient(x_batch, t_batch)
    for key in ('W1', 'b1', 'W2', 'b2'):
        network.params[key] -= learning_rate * grad[key]
        
    loss = network.loss(x_batch, t_batch)
    train_loss_list.append(loss)
    if i % iter_per_eopch == 0:
        train_acc = network.accuracy(x_train, t_train)
        test_acc = network.accuracy(x_test, t_test)
        train_acc_list.sppend(train_acc)
        test_acc_list.append(test_acc)
        print("train acc, test acc | " + str(train_acc) + "," + str(test_acc))